### ISSUE TITLE
Can't find a suitable configuration file  in this directory. The docker-compose.yml is missing

### ISSUE THREAD

**Issue by felopri** [dwisulfahnur/blog-fastapi-vuejs#3]
When I try to lift the service using docker, following the instructions of [README.md](https://github.com/dwisulfahnur/blog-fastapi-vuejs/blob/master/README.md), I get this error:
`$ docker-compose up`
```
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```
Can you publish the docker configuration file? 
Thank you very much!

**Comment by dwisulfahnur** [comment]
Hello,
My apologies for the late response,
The project has been updated included with docker-compose.yml file.

Thank you 😄
